# Utilisez l'image Bitnami du SDK .NET
FROM bitnami/dotnet-sdk:7 AS build
WORKDIR /app

# Copiez les fichiers nécessaires pour restaurer les dépendances
COPY *.csproj ./
RUN dotnet restore

# Copiez tout le reste et construisez l'application
COPY . ./
RUN dotnet publish -c Release -o out

# Utilisez l'image Bitnami du SDK .NET pour exécuter l'application
FROM bitnami/dotnet-sdk:7 AS runtime
WORKDIR /app
COPY --from=build /app/out .

EXPOSE 4000

# Démarrez l'application
ENTRYPOINT ["dotnet", "bin/Debug/net7.0/serviceio.dll"]
