version: '3'

services:
  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./backend:/var/www/html
      - ./fichiers:/var/www/html/fichiers 
    networks:
      - network-io
      - network-app
    #depends_on:
     # - serviceio
    # - servicecalcul

  frontend:
    container_name: frontend
    build: ./frontend/
    restart: always
    volumes:
      - ./frontend:/var/www/html
    ports:
      - 80:80
    networks:
      - network-app

  serviceio:
    container_name: serviceio
    build: ./serviceio/App/
    ports:
      - 82:80
    volumes:
      - ./fichiers:/App/fichiers
    networks:
      - network-io

  # servicecalcul:
  #   build: ./servicecalcul/
  #   restart: always
  #   ports:
  #     - 5000:80
  #   volumes:
  #     - ./servicecalcul:/app
  #   networks:
  #     - mynetwork


networks:
  network-app:
  network-io:
  #network-calcul: