version: '3'

services:
  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./backend:/var/www/html
      - ./fichiers:/var/www/html/fichiers 
    networks:
      - network-io
      - network-app

  frontend:
    container_name: frontend
    build: ./frontend/
    restart: always
    volumes:
      - ./frontend:/var/www/html
    ports:
      - 80:80
    networks:
      - network-app

  serviceio:
    container_name: serviceio
    build: ./serviceio/App/
    ports:
      - 82:80
    volumes:
      - ./fichiers:/App/fichiers
    networks:
      - network-io

  python-app:
    build:
      context: ./python
      dockerfile: dockerfile.python
    ports:
      - 8081:82
    depends_on:
      - backend
    networks:
      - network-app


networks:
  network-app:
  network-io:
  #network-calcul:
