FROM php:apache
WORKDIR /var/www/html

COPY  . /var/www/html
# Copier le fichier de configuration Apache
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

# Définir le répertoire de travail

# Copier les fichiers nécessaires pour Composer
COPY  composer.json /var/www/html/composer.json

RUN apt-get update && \
    apt-get install -y zlib1g-dev libzip-dev && \
    docker-php-ext-install zip && \
    a2enmod rewrite

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && composer install --no-dev --optimize-autoloader
